project:
  type: website
  output-dir: docs
    
website:
  title: "Aulas FIP606"
  favicon: foto.jpg
  navbar:
    pinned: true
    logo: logo.jpg
    left:
      - text: Básico do R
        menu:
          - href: Aula1.qmd
            text: Introdução ao RStudio
          - href: Aula2.qmd
            text: Importação de arquivos
        
      - text: Gráficos em R
        menu:
          - href: Aula3.qmd
            text: Visualização de dados em GGPLOT
          - href: Aula4.qmd
            text: Barra de erro
          - href: Aula5.qmd
            text: Exemplo de análise exploratória
        
      - text: Estatística em R
        menu:
          - href: Aula6.qmd
            text: Estatística inferencial
          - href: Aula7.qmd
            text: Transformações e anova fatorial
          - href: Aula8.qmd
            text: ANOVA em blocos e AUDPC        
          - href: Aula9.qmd
            text: Regressão linear
          - href: Aula10.qmd
            text: Correlação

      - text: Mapas em R
        menu:
          - href: Aula11.qmd
            text: Elaboração de mapas
    right: 
      - icon: github
        href: https://github.com/fecorbelli
      - icon: instagram
        href: https://www.instagram.com/fecorbelli/
        
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
